- hosts: terraform-ansible
  tasks:
    - name: criando arquivo html
      copy:
        dest: /home/ubuntu/index.html
        content: <h1>Feito com Terraform e Ansible, eh verdade esse bilhete</h1>
    - name: criando servidor
      shell: "nohup busybox httpd -f -p 8080 &"